### ISSUE TITLE
Missing chunk data for the block from streamer_message

### ISSUE THREAD

**Issue by Madgeniusblink** [frolvanya/near-lake-framework-py#7]
Hi,

How come in the `shard.chunk` it's only a list of strings and not the actual chunk data from the given block? Because in [near-lake-framework-js ](https://github.com/near/near-lake-framework-js) there is data for chunk.

The data class defined in PY is as follows:
[`chunk: List[str]`](https://github.com/frolvanya/near-lake-framework-py/blob/93a9d3d069679169c21902a54fa83a03b21153bb/src/near_lake_framework/near_primitives.py#L105)

The interface defined in JS is as follow
```
export interface Chunk {
  author: string;
  header: ChunkHeader;
  receipts: Receipt[];
  transactions: IndexerTransactionWithOutcome[];
}
```

**Comment by frolvanya** [comment]
Thanks. I'll take a look
